
# Project ID must be first
project_id = "epfzraejquaxqrfmkmyx"

# Global settings for all functions
[functions]
# Global JWT verification setting (affects all functions unless overridden)
verify_jwt = false
