
# Project ID must be first
project_id = "epfzraejquaxqrfmkmyx"

# Global settings for all functions
[functions]
node_version = 18

[functions.verify_jwt]
enabled = false

[functions.allow_unauthenticated]
enabled = true
