
[build]
  command = "npm install vite@latest --no-save && chmod +x ./scripts/prebuild.sh && ./scripts/prebuild.sh && npx vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# This ensures our prebuild script has the required permissions
[[plugins]]
package = "@netlify/plugin-functions-install-core"

# Debug build output
[context.production.environment]
  NODE_ENV = "production"
  DEBUG = "true"
