
[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

# This ensures our prebuild script has the required permissions
[[plugins]]
package = "@netlify/plugin-functions-install-core"

# Debug build output
[context.production.environment]
  NODE_ENV = "production"
  DEBUG = "true"
