
[build]
  command = "npm install && npx vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max-old-space-size=4096"

# This ensures our prebuild script has the required permissions
[[plugins]]
package = "@netlify/plugin-functions-install-core"

# Debug build output
[context.production.environment]
  NODE_ENV = "production"
  DEBUG = "true"
