
[build]
  command = "chmod +x ./scripts/prebuild.sh && ./scripts/prebuild.sh && npx vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"
  NODE_ENV = "production"  # Run in production mode

# This ensures our prebuild script has the required permissions
[[plugins]]
package = "@netlify/plugin-functions-install-core"

# Add cache headers for static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Set appropriate caching for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# More debugging info for build process
[context.production.environment]
  DEBUG = "*"
