
# Function-specific settings (must match parent project ID)
project_id = "epfzraejquaxqrfmkmyx"

[verify_jwt]
enabled = false

[allow_unauthenticated]
enabled = true

import_map = "../import_map.json"
