
# Project ID must be first
project_id = "epfzraejquaxqrfmkmyx"

# Global settings - apply to all functions
verify_jwt = false
allow_unauthenticated = true

# Function-specific settings with explicit public access
[functions."everflow-webhook"]
verify_jwt = false
allow_unauthenticated = true
import_map = "../import_map.json"
