
# This is the crucial setting - it allows the function to be accessed without authentication
verify_jwt = false
# This setting ensures the function is publicly accessible without any Supabase key verification
allow_unauthenticated = true

# Additional settings - not strictly necessary but good to be explicit
[functions."*"]
verify_jwt = false
