
# Project ID must be first
project_id = "epfzraejquaxqrfmkmyx"

# Critical public access settings
verify_jwt = false
allow_unauthenticated = true

# Global settings to ensure all functions have public access
[functions."everflow-webhook"]
verify_jwt = false
allow_unauthenticated = true

# Explicit wildcard configuration
[functions."*"]
verify_jwt = false
allow_unauthenticated = true
