
# Function-specific settings
project_id = "epfzraejquaxqrfmkmyx"

# This function requires authentication
[verify_jwt]
enabled = true

allow_unauthenticated = false

import_map = "../import_map.json"
