
# Function-specific settings (must match parent project ID)
project_id = "epfzraejquaxqrfmkmyx"

# Explicitly disable JWT verification using consistent syntax
verify_jwt = false

allow_unauthenticated = true

import_map = "../import_map.json"

